language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
before_script:
  - npm run build:all
after_success:
  - npm run coverage
  - npm publish
branches:
  only:
    - master
    - /^deploy-.*$/
