language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '8'
before_script:
  - npm run build:all
after_success:
  - npm run coverage
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  - production
